/**
 * Crypto Compass — Quiz Catalog (Phase 14)
 *
 * 15 Structured Educational Quizzes mapped 1:1 to Phase 13 Lessons:
 * - 4 Crypto Fundamentals
 * - 3 Market Basics
 * - 4 Trading Fundamentals
 * - 2 Risk Management
 * - 2 Trading Discipline
 *
 * Each quiz contains exactly 5 multiple-choice questions (4 options each).
 * Strictly educational: zero financial advice, zero predictions, zero guaranteed returns.
 */

const QUIZZES = [
  // =========================================================================
  // CATEGORY 1: CRYPTO FUNDAMENTALS (4 Quizzes)
  // =========================================================================
  {
    id: 'quiz-what-is-cryptocurrency',
    lessonId: 'what-is-cryptocurrency',
    title: 'What Is Cryptocurrency? — Assessment',
    category: 'crypto_fundamentals',
    categoryLabel: 'Crypto Fundamentals',
    difficulty: 'BEGINNER',
    estimatedMinutes: 3,
    description: 'Check your understanding of decentralized digital money, cryptography, and how cryptocurrencies differ from fiat currencies.',
    questions: [
      {
        id: 'q1',
        question: 'What is the primary technical mechanism used to secure cryptocurrency transactions?',
        options: [
          { id: 'opt1', text: 'Central bank administrative approvals' },
          { id: 'opt2', text: 'Mathematical cryptography' },
          { id: 'opt3', text: 'Government regulatory audits' },
          { id: 'opt4', text: 'Physical bank security vaults' },
        ],
        correctOptionId: 'opt2',
        explanation: 'Cryptocurrency relies on mathematical cryptography rather than central intermediaries to secure balances and verify transactions.',
      },
      {
        id: 'q2',
        question: 'How do cryptocurrencies fundamentally differ from traditional fiat money like the US Dollar?',
        options: [
          { id: 'opt1', text: 'Cryptocurrencies are physically printed on polymer banknotes' },
          { id: 'opt2', text: 'Cryptocurrencies typically run on decentralized computer networks without central bank issuance' },
          { id: 'opt3', text: 'Cryptocurrencies cannot be transferred across national borders' },
          { id: 'opt4', text: 'Cryptocurrencies can only be used by commercial financial corporations' },
        ],
        correctOptionId: 'opt2',
        explanation: 'Unlike traditional fiat currencies managed by central authorities, cryptocurrencies operate on open, decentralized networks.',
      },
      {
        id: 'q3',
        question: 'What replaces trusted human intermediaries in a cryptocurrency network?',
        options: [
          { id: 'opt1', text: 'Cryptographic proof and algorithmic network consensus' },
          { id: 'opt2', text: 'Quarterly corporate board resolutions' },
          { id: 'opt3', text: 'Verbal agreements between peer traders' },
          { id: 'opt4', text: 'Manual ledger reviews performed by local bank tellers' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Cryptographic keys and mathematical consensus algorithms replace the need for trusted institutional middlemen.',
      },
      {
        id: 'q4',
        question: 'Why must beginners exercise caution when transferring cryptocurrency?',
        options: [
          { id: 'opt1', text: 'All crypto transactions can be reversed by bank customer service within 30 days' },
          { id: 'opt2', text: 'Confirmed cryptocurrency transactions are typically immutable and irreversible' },
          { id: 'opt3', text: 'Transfers require written authorization from a notary public' },
          { id: 'opt4', text: 'Transactions only occur during traditional equity market hours' },
        ],
        correctOptionId: 'opt2',
        explanation: 'Because decentralized blockchains do not have a central administrator, confirmed transactions cannot be arbitrarily undone.',
      },
      {
        id: 'q5',
        question: 'What does decentralization help eliminate in financial record-keeping?',
        options: [
          { id: 'opt1', text: 'The possibility of price fluctuations' },
          { id: 'opt2', text: 'Single points of institutional failure or unilateral control' },
          { id: 'opt3', text: 'The need for computing hardware or network nodes' },
          { id: 'opt4', text: 'All operational software updates' },
        ],
        correctOptionId: 'opt2',
        explanation: 'Decentralized architectures distribute ledger maintenance across thousands of nodes, eliminating a single point of failure.',
      },
    ],
  },
  {
    id: 'quiz-how-blockchain-works',
    lessonId: 'how-blockchain-works',
    title: 'How Blockchain Works — Assessment',
    category: 'crypto_fundamentals',
    categoryLabel: 'Crypto Fundamentals',
    difficulty: 'BEGINNER',
    estimatedMinutes: 3,
    description: 'Assess your knowledge of distributed ledgers, cryptographic block hashing, and consensus protocols.',
    questions: [
      {
        id: 'q1',
        question: 'What is a blockchain at its most fundamental conceptual level?',
        options: [
          { id: 'opt1', text: 'An append-only distributed ledger shared across network nodes' },
          { id: 'opt2', text: 'A private spreadsheet stored on a single company server' },
          { id: 'opt3', text: 'A high-frequency algorithmic trade matching engine' },
          { id: 'opt4', text: 'A proprietary web browser for digital asset trading' },
        ],
        correctOptionId: 'opt1',
        explanation: 'A blockchain is an append-only distributed ledger where valid transactions are sequentially added in blocks.',
      },
      {
        id: 'q2',
        question: 'How are individual blocks linked together cryptographically?',
        options: [
          { id: 'opt1', text: 'Each block contains the cryptographic hash fingerprint of the previous block' },
          { id: 'opt2', text: 'Blocks are physically connected through optical fiber cables' },
          { id: 'opt3', text: 'Blocks are tagged with an external banking routing number' },
          { id: 'opt4', text: 'Blocks are verified only when printed onto physical paper' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Each block includes the hash of the preceding block, forming a tamper-evident cryptographic chain.',
      },
      {
        id: 'q3',
        question: 'What happens if a bad actor attempts to alter a historical transaction in an older block?',
        options: [
          { id: 'opt1', text: 'The entire historical blockchain updates automatically to match the alteration' },
          { id: 'opt2', text: 'The block hash changes, invalidating all subsequent blocks and causing network nodes to reject it' },
          { id: 'opt3', text: 'The network grants the bad actor administrator privileges' },
          { id: 'opt4', text: 'The blockchain network temporarily pauses for manual reconciliation' },
        ],
        correctOptionId: 'opt2',
        explanation: 'Modifying past data alters the cryptographic hash, breaking subsequent links and causing independent nodes to reject the tampered chain.',
      },
      {
        id: 'q4',
        question: 'What is the primary role of a consensus mechanism (like Proof of Work or Proof of Stake)?',
        options: [
          { id: 'opt1', text: 'To predict future cryptocurrency market valuations' },
          { id: 'opt2', text: 'To allow independent nodes to agree on the valid transaction order without a central coordinator' },
          { id: 'opt3', text: 'To calculate exchange transaction fee discounts' },
          { id: 'opt4', text: 'To generate personalized trading advice for retail investors' },
        ],
        correctOptionId: 'opt2',
        explanation: 'Consensus algorithms enable decentralized computers to reach agreement on transaction validity and ledger sequence.',
      },
      {
        id: 'q5',
        question: 'In Proof of Stake consensus, what do validators use to help secure the network?',
        options: [
          { id: 'opt1', text: 'Dedicated physical printing presses' },
          { id: 'opt2', text: 'Locked token collateral (stake)' },
          { id: 'opt3', text: 'Credit scores from consumer credit bureaus' },
          { id: 'opt4', text: 'Annual corporate surety bonds' },
        ],
        correctOptionId: 'opt2',
        explanation: 'Proof of Stake validators commit their own cryptocurrency tokens as collateral (stake) to validate blocks truthfully.',
      },
    ],
  },
  {
    id: 'quiz-bitcoin-vs-altcoins',
    lessonId: 'bitcoin-vs-altcoins',
    title: 'Bitcoin vs Altcoins — Assessment',
    category: 'crypto_fundamentals',
    categoryLabel: 'Crypto Fundamentals',
    difficulty: 'BEGINNER',
    estimatedMinutes: 3,
    description: 'Test your understanding of Bitcoin’s role as digital gold versus programmable altcoin platforms and smart contracts.',
    questions: [
      {
        id: 'q1',
        question: 'What is the maximum supply limit of Bitcoin enforced by its protocol rules?',
        options: [
          { id: 'opt1', text: '100 million coins' },
          { id: 'opt2', text: '21 million coins' },
          { id: 'opt3', text: 'Unlimited coins adjusted annually by inflation' },
          { id: 'opt4', text: '1 billion coins' },
        ],
        correctOptionId: 'opt2',
        explanation: 'Bitcoin has a mathematically hard-capped total supply limit of 21 million coins.',
      },
      {
        id: 'q2',
        question: 'What does the term "altcoin" refer to in the cryptocurrency ecosystem?',
        options: [
          { id: 'opt1', text: 'Any digital asset or cryptocurrency other than Bitcoin' },
          { id: 'opt2', text: 'Coins issued exclusively by international central banks' },
          { id: 'opt3', text: 'Tokens that have no connection to blockchain technology' },
          { id: 'opt4', text: 'Physical silver and bronze commemorative coins' },
        ],
        correctOptionId: 'opt1',
        explanation: 'The term "altcoin" (alternative coin) broadly encompasses all cryptocurrencies outside of Bitcoin.',
      },
      {
        id: 'q3',
        question: 'What groundbreaking functionality did Ethereum introduce to blockchain technology?',
        options: [
          { id: 'opt1', text: 'Paper checks for peer-to-peer payments' },
          { id: 'opt2', text: 'Programmable smart contracts and decentralized applications' },
          { id: 'opt3', text: 'Elimination of all network transaction fees' },
          { id: 'opt4', text: 'Mandatory government identity registration' },
        ],
        correctOptionId: 'opt2',
        explanation: 'Ethereum introduced a Turing-complete virtual machine enabling self-executing code (smart contracts) and dApps.',
      },
      {
        id: 'q4',
        question: 'Why is Bitcoin often compared to "digital gold"?',
        options: [
          { id: 'opt1', text: 'It has physical chemical properties identical to mineral gold' },
          { id: 'opt2', text: 'It emphasizes scarcity, predictability, and long-term store-of-value characteristics' },
          { id: 'opt3', text: 'It is backed by physical gold stored in depository vaults' },
          { id: 'opt4', text: 'It was created by sovereign mining corporations' },
        ],
        correctOptionId: 'opt2',
        explanation: 'Bitcoin’s capped supply, monetary predictability, and decentralized custody make it analogous to digital gold.',
      },
      {
        id: 'q5',
        question: 'Why do different altcoins have diverse technological designs?',
        options: [
          { id: 'opt1', text: 'All cryptocurrencies are exact byte-for-byte copies of each other' },
          { id: 'opt2', text: 'Different projects target distinct use cases, throughput goals, and technical trade-offs' },
          { id: 'opt3', text: 'Altcoin software code is strictly dictated by global treaties' },
          { id: 'opt4', text: 'There are no technological differences between any crypto assets' },
        ],
        correctOptionId: 'opt2',
        explanation: 'Different crypto networks optimize for various trade-offs such as transaction throughput, privacy, smart contract flexibility, or governance.',
      },
    ],
  },
  {
    id: 'quiz-crypto-wallets-explained',
    lessonId: 'crypto-wallets-explained',
    title: 'Crypto Wallets Explained — Assessment',
    category: 'crypto_fundamentals',
    categoryLabel: 'Crypto Fundamentals',
    difficulty: 'BEGINNER',
    estimatedMinutes: 3,
    description: 'Check your knowledge of public addresses, private keys, seed phrases, and the distinction between custodial and non-custodial custody.',
    questions: [
      {
        id: 'q1',
        question: 'What does a crypto wallet actually store?',
        options: [
          { id: 'opt1', text: 'Physical coins inside your computer hard drive' },
          { id: 'opt2', text: 'Cryptographic keys that prove ownership and authorize transfers on the blockchain' },
          { id: 'opt3', text: 'Digital JPEG files of paper currency' },
          { id: 'opt4', text: 'Government identification documents' },
        ],
        correctOptionId: 'opt2',
        explanation: 'Coins live on the blockchain; crypto wallets store the cryptographic keypairs used to access and transfer those on-chain funds.',
      },
      {
        id: 'q2',
        question: 'Which of the following is safe to share publicly with someone sending you funds?',
        options: [
          { id: 'opt1', text: 'Your private key' },
          { id: 'opt2', text: 'Your 12- or 24-word recovery seed phrase' },
          { id: 'opt3', text: 'Your public receiving address' },
          { id: 'opt4', text: 'Your hardware wallet master PIN code' },
        ],
        correctOptionId: 'opt3',
        explanation: 'A public address is like an account number or email; it can be safely shared to receive funds.',
      },
      {
        id: 'q3',
        question: 'What is the primary responsibility of a private key?',
        options: [
          { id: 'opt1', text: 'To calculate daily exchange rate averages' },
          { id: 'opt2', text: 'To cryptographically sign and authorize outgoing transactions from your address' },
          { id: 'opt3', text: 'To look up market capitalization rankings' },
          { id: 'opt4', text: 'To change your username on public forums' },
        ],
        correctOptionId: 'opt2',
        explanation: 'Private keys generate cryptographic digital signatures required to spend or transfer assets from an address.',
      },
      {
        id: 'q4',
        question: 'What characterizes a self-custody (non-custodial) wallet?',
        options: [
          { id: 'opt1', text: 'A commercial bank holds your password and can reset it on phone request' },
          { id: 'opt2', text: 'You alone control the private keys and bear sole responsibility for backup and recovery' },
          { id: 'opt3', text: 'The exchange holds your funds in an omnibus pooled account' },
          { id: 'opt4', text: 'All transactions are monitored by credit card networks' },
        ],
        correctOptionId: 'opt2',
        explanation: 'With self-custody, only the user holds the private keys, eliminating third-party custody risk but requiring personal backup discipline.',
      },
      {
        id: 'q5',
        question: 'What is a recovery seed phrase used for?',
        options: [
          { id: 'opt1', text: 'To cancel a confirmed blockchain transaction' },
          { id: 'opt2', text: 'To reconstruct all private keys and wallet balances if your device is lost or damaged' },
          { id: 'opt3', text: 'To bypass network gas fees on Ethereum' },
          { id: 'opt4', text: 'To earn guaranteed staking returns' },
        ],
        correctOptionId: 'opt2',
        explanation: 'A recovery seed phrase encodes the master seed needed to restore private keys and wallet access on a new device.',
      },
    ],
  },

  // =========================================================================
  // CATEGORY 2: MARKET BASICS (3 Quizzes)
  // =========================================================================
  {
    id: 'quiz-understanding-crypto-prices',
    lessonId: 'understanding-crypto-prices',
    title: 'Understanding Crypto Prices — Assessment',
    category: 'market_basics',
    categoryLabel: 'Market Basics',
    difficulty: 'BEGINNER',
    estimatedMinutes: 3,
    description: 'Assess your comprehension of supply and demand dynamics, order books, and how market clearing prices form.',
    questions: [
      {
        id: 'q1',
        question: 'How is the market price of a cryptocurrency primarily determined on an exchange?',
        options: [
          { id: 'opt1', text: 'By a central price committee meeting weekly' },
          { id: 'opt2', text: 'By the continuous interaction of buyers and sellers through supply and demand' },
          { id: 'opt3', text: 'By the physical manufacturing cost of silicon chips' },
          { id: 'opt4', text: 'By mathematical formula based on calendar dates' },
        ],
        correctOptionId: 'opt2',
        explanation: 'Market prices emerge from continuous order matching between buyers and sellers on exchange order books.',
      },
      {
        id: 'q2',
        question: 'What happens in a market when buying demand significantly exceeds selling supply at current prices?',
        options: [
          { id: 'opt1', text: 'Trading is permanently closed' },
          { id: 'opt2', text: 'Price tends to experience upward pressure as buyers compete for available supply' },
          { id: 'opt3', text: 'All transactions are refunded' },
          { id: 'opt4', text: 'The total coin supply automatically quadruples' },
        ],
        correctOptionId: 'opt2',
        explanation: 'When demand outpaces supply, buyers must bid higher prices to incentivize sellers to execute trades.',
      },
      {
        id: 'q3',
        question: 'What does the bid price represent in an exchange order book?',
        options: [
          { id: 'opt1', text: 'The highest price a buyer is currently willing to pay' },
          { id: 'opt2', text: 'The lowest price a seller is willing to accept' },
          { id: 'opt3', text: 'The average price of all transactions over the last year' },
          { id: 'opt4', text: 'The withdrawal fee charged by the exchange' },
        ],
        correctOptionId: 'opt1',
        explanation: 'The bid is the highest price currently offered by prospective buyers on the order book.',
      },
      {
        id: 'q4',
        question: 'What does the ask (offer) price represent in an exchange order book?',
        options: [
          { id: 'opt1', text: 'The lowest price a seller is currently willing to accept' },
          { id: 'opt2', text: 'The highest price a buyer has ever bid' },
          { id: 'opt3', text: 'The protocol inflation rate' },
          { id: 'opt4', text: 'The balance of the virtual wallet' },
        ],
        correctOptionId: 'opt1',
        explanation: 'The ask is the lowest price at which a seller is willing to part with their crypto asset.',
      },
      {
        id: 'q5',
        question: 'What is the difference between the highest bid and the lowest ask called?',
        options: [
          { id: 'opt1', text: 'The bid-ask spread' },
          { id: 'opt2', text: 'The dividend yield' },
          { id: 'opt3', text: 'The hash rate' },
          { id: 'opt4', text: 'The collateral ratio' },
        ],
        correctOptionId: 'opt1',
        explanation: 'The bid-ask spread is the gap between the highest price a buyer is offering and the lowest price a seller is asking.',
      },
    ],
  },
  {
    id: 'quiz-market-capitalization-explained',
    lessonId: 'market-capitalization-explained',
    title: 'Market Capitalization Explained — Assessment',
    category: 'market_basics',
    categoryLabel: 'Market Basics',
    difficulty: 'BEGINNER',
    estimatedMinutes: 3,
    description: 'Test your understanding of market cap calculations, circulating supply, and avoiding unit-bias pitfalls.',
    questions: [
      {
        id: 'q1',
        question: 'How is the market capitalization (market cap) of a cryptocurrency calculated?',
        options: [
          { id: 'opt1', text: 'Current Unit Price × Circulating Coin Supply' },
          { id: 'opt2', text: '24-Hour Trading Volume ÷ Total Wallets' },
          { id: 'opt3', text: 'Highest Historical Price + Lowest Historical Price' },
          { id: 'opt4', text: 'Total Transactions ÷ Exchange Fee Rate' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Market cap is simply the current price per unit multiplied by the total circulating number of coins or tokens.',
      },
      {
        id: 'q2',
        question: 'Why is comparing coins solely based on unit price misleading (the "unit bias" fallacy)?',
        options: [
          { id: 'opt1', text: 'Because all cryptocurrencies have identical coin supplies' },
          { id: 'opt2', text: 'Because a coin with a $0.001 price might have a massive supply and a larger market cap than a $100 coin' },
          { id: 'opt3', text: 'Because prices are fixed by law' },
          { id: 'opt4', text: 'Because unit prices are only updated once per month' },
        ],
        correctOptionId: 'opt2',
        explanation: 'A low per-coin price does not mean a coin is cheap or has more room to grow; supply determines the aggregate valuation.',
      },
      {
        id: 'q3',
        question: 'If Asset A has a unit price of $10 with 1,000,000 coins in circulation, what is its market cap?',
        options: [
          { id: 'opt1', text: '$100,000' },
          { id: 'opt2', text: '$1,000,000' },
          { id: 'opt3', text: '$10,000,000' },
          { id: 'opt4', text: '$100,000,000' },
        ],
        correctOptionId: 'opt3',
        explanation: '$10 price × 1,000,000 circulating supply = $10,000,000 market capitalization.',
      },
      {
        id: 'q4',
        question: 'What is circulating supply as defined in digital asset metrics?',
        options: [
          { id: 'opt1', text: 'The number of coins currently publicly available and circulating in the market' },
          { id: 'opt2', text: 'The total number of coins that will ever exist in 100 years' },
          { id: 'opt3', text: 'The number of paper bills printed by mints' },
          { id: 'opt4', text: 'The number of registered users on an exchange' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Circulating supply refers to tokens that are currently unlocked and tradable in the open market.',
      },
      {
        id: 'q5',
        question: 'What does fully diluted valuation (FDV) estimate?',
        options: [
          { id: 'opt1', text: 'The market cap if the maximum theoretical supply of all tokens were in circulation today' },
          { id: 'opt2', text: 'The amount of cash in an exchange’s physical bank account' },
          { id: 'opt3', text: 'The maximum loss possible on a paper trade' },
          { id: 'opt4', text: 'The total transaction fees paid since network genesis' },
        ],
        correctOptionId: 'opt1',
        explanation: 'FDV calculates current price multiplied by the maximum eventual supply of the crypto asset.',
      },
    ],
  },
  {
    id: 'quiz-volatility-explained',
    lessonId: 'volatility-explained',
    title: 'Volatility Explained — Assessment',
    category: 'market_basics',
    categoryLabel: 'Market Basics',
    difficulty: 'BEGINNER',
    estimatedMinutes: 3,
    description: 'Assess your grasp of market volatility, rapid price swings, liquidity impacts, and risk awareness.',
    questions: [
      {
        id: 'q1',
        question: 'What does market volatility measure in cryptocurrency trading?',
        options: [
          { id: 'opt1', text: 'The physical temperature of server computer processors' },
          { id: 'opt2', text: 'The frequency and magnitude of price fluctuations over a period of time' },
          { id: 'opt3', text: 'The exact percentage of guaranteed investment gains' },
          { id: 'opt4', text: 'The total number of coins held by wallet developers' },
        ],
        correctOptionId: 'opt2',
        explanation: 'Volatility measures how rapidly and dramatically prices swing up and down over a given time interval.',
      },
      {
        id: 'q2',
        question: 'Why do cryptocurrency markets typically exhibit higher volatility than traditional equity or bond markets?',
        options: [
          { id: 'opt1', text: 'Cryptocurrency markets trade 24/7 globally and have emerging liquidity and evolving adoption' },
          { id: 'opt2', text: 'Traditional stock markets do not allow price changes' },
          { id: 'opt3', text: 'All crypto market prices are set by central bank algorithms' },
          { id: 'opt4', text: 'Cryptocurrencies cannot experience trading volume' },
        ],
        correctOptionId: 'opt1',
        explanation: '24/7 global trading, continuous news flow, and developing liquidity depth contribute to higher price variance in crypto.',
      },
      {
        id: 'q3',
        question: 'How does low market liquidity in an asset affect its volatility?',
        options: [
          { id: 'opt1', text: 'It completely stabilizes the price permanently' },
          { id: 'opt2', text: 'It can amplify volatility because modest buy or sell orders can move prices significantly' },
          { id: 'opt3', text: 'It prevents all orders from executing' },
          { id: 'opt4', text: 'It automatically guarantees a profitable exit' },
        ],
        correctOptionId: 'opt2',
        explanation: 'Thin order books with low liquidity mean individual orders consume existing levels quickly, causing larger price jumps.',
      },
      {
        id: 'q4',
        question: 'How should a disciplined beginner view high market volatility?',
        options: [
          { id: 'opt1', text: 'As a guaranteed opportunity to double money every week' },
          { id: 'opt2', text: 'As a risk factor requiring conservative position sizing and strict capital preservation rules' },
          { id: 'opt3', text: 'As an indicator that stop-loss principles should be ignored' },
          { id: 'opt4', text: 'As proof that research is unnecessary' },
        ],
        correctOptionId: 'opt2',
        explanation: 'High volatility represents two-sided risk; disciplined traders respond with smaller position sizes and risk management.',
      },
      {
        id: 'q5',
        question: 'What educational tool helps paper traders experience market volatility safely without losing money?',
        options: [
          { id: 'opt1', text: 'Margin leverage with real capital loans' },
          { id: 'opt2', text: 'Simulated paper trading using virtual portfolio funds' },
          { id: 'opt3', text: 'Paid signal chatrooms on messaging apps' },
          { id: 'opt4', text: 'Unverified automated trading software bots' },
        ],
        correctOptionId: 'opt2',
        explanation: 'Paper trading environments like Crypto Compass let learners observe real price volatility using risk-free simulated funds.',
      },
    ],
  },

  // =========================================================================
  // CATEGORY 3: TRADING FUNDAMENTALS (4 Quizzes)
  // =========================================================================
  {
    id: 'quiz-what-is-spot-trading',
    lessonId: 'what-is-spot-trading',
    title: 'What Is Spot Trading? — Assessment',
    category: 'trading_fundamentals',
    categoryLabel: 'Trading Fundamentals',
    difficulty: 'BEGINNER',
    estimatedMinutes: 3,
    description: 'Evaluate your understanding of spot market exchange, immediate settlement, and real asset ownership.',
    questions: [
      {
        id: 'q1',
        question: 'What happens in a spot market transaction when a trade executes?',
        options: [
          { id: 'opt1', text: 'Buyer and seller exchange the actual asset for cash with immediate settlement' },
          { id: 'opt2', text: 'The trade settles only after a 5-year holding period' },
          { id: 'opt3', text: 'No assets or funds are ever exchanged' },
          { id: 'opt4', text: 'The buyer is required to borrow 100x leverage from a broker' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Spot trading refers to the purchase or sale of a financial asset for direct and immediate settlement "on the spot."',
      },
      {
        id: 'q2',
        question: 'How does spot trading fundamentally differ from derivative trading (like futures or options contracts)?',
        options: [
          { id: 'opt1', text: 'Spot trading involves direct ownership of the underlying asset rather than a contract based on its price' },
          { id: 'opt2', text: 'Spot trading requires physical gold delivery' },
          { id: 'opt3', text: 'Futures contracts never expire, whereas spot trades expire weekly' },
          { id: 'opt4', text: 'Spot trading does not use market or limit orders' },
        ],
        correctOptionId: 'opt1',
        explanation: 'In spot markets you take ownership of the actual cryptocurrency, whereas derivatives trade agreements based on future price movements.',
      },
      {
        id: 'q3',
        question: 'Can you lose more money than your initial purchase in an unleveraged spot cryptocurrency trade?',
        options: [
          { id: 'opt1', text: 'Yes, your account balance can drop into negative debt to the exchange' },
          { id: 'opt2', text: 'No, in unleveraged spot trading your maximum loss is capped at the total amount you invested' },
          { id: 'opt3', text: 'Yes, if market volatility exceeds 10%' },
          { id: 'opt4', text: 'No, spot trades never lose any value under any circumstances' },
        ],
        correctOptionId: 'opt2',
        explanation: 'Without leverage or borrowing, the most an unleveraged spot holding can lose is 100% of the invested amount (it cannot go negative).',
      },
      {
        id: 'q4',
        question: 'In Crypto Compass, what type of market is simulated for learners?',
        options: [
          { id: 'opt1', text: 'Complex leveraged collateralized debt obligations' },
          { id: 'opt2', text: 'Simulated spot crypto trading with virtual cash balances' },
          { id: 'opt3', text: 'Real-money binary options contracts' },
          { id: 'opt4', text: 'High-frequency algorithmic market-making pools' },
        ],
        correctOptionId: 'opt2',
        explanation: 'Crypto Compass simulates spot trading so learners can understand asset ownership and order execution without debt or leverage risk.',
      },
      {
        id: 'q5',
        question: 'What is a trading pair such as BTC/USD in spot trading?',
        options: [
          { id: 'opt1', text: 'A quote showing how many units of quote currency (USD) are needed to buy one unit of base asset (BTC)' },
          { id: 'opt2', text: 'A requirement that you must buy two different cryptocurrencies simultaneously' },
          { id: 'opt3', text: 'The username and password used to log in' },
          { id: 'opt4', text: 'A legal contract between two commercial banks' },
        ],
        correctOptionId: 'opt1',
        explanation: 'A pair defines the exchange rate between the base asset (BTC) and the quote pricing currency (USD).',
      },
    ],
  },
  {
    id: 'quiz-market-orders-explained',
    lessonId: 'market-orders-explained',
    title: 'Market Orders Explained — Assessment',
    category: 'trading_fundamentals',
    categoryLabel: 'Trading Fundamentals',
    difficulty: 'BEGINNER',
    estimatedMinutes: 3,
    description: 'Check your knowledge of market order execution, instant fills, price slippage, and taker fees.',
    questions: [
      {
        id: 'q1',
        question: 'What is the primary objective of submitting a market order?',
        options: [
          { id: 'opt1', text: 'To guarantee execution at a specific future price target' },
          { id: 'opt2', text: 'To execute immediately at the best currently available market prices' },
          { id: 'opt3', text: 'To cancel all previous trades on the exchange' },
          { id: 'opt4', text: 'To avoid all network confirmation processes' },
        ],
        correctOptionId: 'opt2',
        explanation: 'Market orders prioritize immediate speed of execution over specific price guarantees.',
      },
      {
        id: 'q2',
        question: 'What is "slippage" when executing a market order?',
        options: [
          { id: 'opt1', text: 'A hardware error when clicking the computer mouse' },
          { id: 'opt2', text: 'The difference between expected price and the actual execution price due to available order book depth' },
          { id: 'opt3', text: 'An intentional fee charged by internet service providers' },
          { id: 'opt4', text: 'A discount given to first-time traders' },
        ],
        correctOptionId: 'opt2',
        explanation: 'Slippage occurs when an order fills across multiple price tiers in the order book, resulting in an average fill price different from the top of the book.',
      },
      {
        id: 'q3',
        question: 'When might a trader decide to use a market order instead of a limit order?',
        options: [
          { id: 'opt1', text: 'When instant entry or exit is more critical than waiting for a specific price' },
          { id: 'opt2', text: 'When the trader wants to wait several days for a dip' },
          { id: 'opt3', text: 'When the trader wants zero transaction fees guaranteed' },
          { id: 'opt4', text: 'When trading assets with zero order book volume' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Market orders are used when guaranteed, immediate execution is the trader’s paramount priority.',
      },
      {
        id: 'q4',
        question: 'Does a market buy order match against existing bids or existing asks in the order book?',
        options: [
          { id: 'opt1', text: 'It matches against existing sell orders (asks)' },
          { id: 'opt2', text: 'It matches against existing buy orders (bids)' },
          { id: 'opt3', text: 'It creates a new passive order that waits indefinitely' },
          { id: 'opt4', text: 'It matches against central bank foreign reserves' },
        ],
        correctOptionId: 'opt1',
        explanation: 'A market buy consumes available liquidity from the sell side (the asks) on the order book.',
      },
      {
        id: 'q5',
        question: 'Why can executing very large market orders in illiquid markets be dangerous for capital?',
        options: [
          { id: 'opt1', text: 'The order can eat through thin order books, resulting in severe negative slippage and worse average fill prices' },
          { id: 'opt2', text: 'The exchange will confiscate the trader’s computer' },
          { id: 'opt3', text: 'The price will remain completely frozen' },
          { id: 'opt4', text: 'It forces the user to switch to a paper trading account' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Large market orders in low-depth markets can sweep multiple price levels, causing substantial adverse price impact.',
      },
    ],
  },
  {
    id: 'quiz-buy-vs-sell',
    lessonId: 'buy-vs-sell',
    title: 'Buy vs Sell Orders — Assessment',
    category: 'trading_fundamentals',
    categoryLabel: 'Trading Fundamentals',
    difficulty: 'BEGINNER',
    estimatedMinutes: 3,
    description: 'Test your understanding of buying to establish positions, selling to close or rebalance, and trade mechanics.',
    questions: [
      {
        id: 'q1',
        question: 'In spot trading, what does executing a BUY order accomplish?',
        options: [
          { id: 'opt1', text: 'Exchanges quote currency (cash) to acquire and hold the base cryptocurrency' },
          { id: 'opt2', text: 'Borrows cryptocurrency from the exchange to return later' },
          { id: 'opt3', text: 'Permanently locks funds with no ability to sell' },
          { id: 'opt4', text: 'Cancels all pending blockchain network transactions' },
        ],
        correctOptionId: 'opt1',
        explanation: 'A buy order allocates virtual cash to purchase a specified quantity of a digital asset.',
      },
      {
        id: 'q2',
        question: 'What does executing a SELL order accomplish in a spot portfolio?',
        options: [
          { id: 'opt1', text: 'Exchanges an existing crypto holding back into quote currency (cash)' },
          { id: 'opt2', text: 'Doubles the amount of crypto held in storage' },
          { id: 'opt3', text: 'Transfers ownership to a foreign bank account' },
          { id: 'opt4', text: 'Guarantees that the market price will decline' },
        ],
        correctOptionId: 'opt1',
        explanation: 'A sell order liquidates part or all of a cryptocurrency position back into cash.',
      },
      {
        id: 'q3',
        question: 'Can you execute a spot SELL order for an asset you do not currently hold in your portfolio?',
        options: [
          { id: 'opt1', text: 'No, in spot trading you can only sell assets you already own in your portfolio' },
          { id: 'opt2', text: 'Yes, spot exchanges allow unlimited naked shorting with zero collateral' },
          { id: 'opt3', text: 'Yes, if you enter a negative quantity' },
          { id: 'opt4', text: 'Yes, but only during weekends' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Spot selling requires owning the asset; you cannot sell what you do not have.',
      },
      {
        id: 'q4',
        question: 'What is the "average buy price" (cost basis) of a crypto position?',
        options: [
          { id: 'opt1', text: 'The average price paid per unit across all purchases of that asset' },
          { id: 'opt2', text: 'The all-time high price recorded in market history' },
          { id: 'opt3', text: 'The exchange withdrawal fee multiplied by transaction count' },
          { id: 'opt4', text: 'The price target recommended by anonymous social media influencers' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Average buy price represents the weighted average acquisition cost per coin of your holding.',
      },
      {
        id: 'q5',
        question: 'Why do disciplined traders sell portions of winning positions (partial profit-taking)?',
        options: [
          { id: 'opt1', text: 'To de-risk capital, lock in gains to cash, and reduce exposure to future volatility' },
          { id: 'opt2', text: 'Because exchanges require all accounts to sell daily' },
          { id: 'opt3', text: 'To permanently close their trading account' },
          { id: 'opt4', text: 'To trigger automated margin calls' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Selling portions into strength rebalances portfolio risk and locks in virtual capital.',
      },
    ],
  },
  {
    id: 'quiz-understanding-trading-volume',
    lessonId: 'understanding-trading-volume',
    title: 'Understanding Trading Volume — Assessment',
    category: 'trading_fundamentals',
    categoryLabel: 'Trading Fundamentals',
    difficulty: 'BEGINNER',
    estimatedMinutes: 3,
    description: 'Assess your comprehension of trading volume, market activity confirmation, and liquidity reliability.',
    questions: [
      {
        id: 'q1',
        question: 'What does trading volume represent on a market chart?',
        options: [
          { id: 'opt1', text: 'The total amount of an asset traded between buyers and sellers over a specific timeframe' },
          { id: 'opt2', text: 'The audio loudness of the exchange server room' },
          { id: 'opt3', text: 'The maximum speed of the user’s internet connection' },
          { id: 'opt4', text: 'The percentage interest rate charged on fiat bank deposits' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Volume measures the total quantity or dollar value of assets transacted over a defined period (e.g. 24 hours).',
      },
      {
        id: 'q2',
        question: 'What does high trading volume generally suggest about market consensus during a price move?',
        options: [
          { id: 'opt1', text: 'There is strong market participation and high liquidity behind the price movement' },
          { id: 'opt2', text: 'The exchange is experiencing technical server downtime' },
          { id: 'opt3', text: 'No trades were executed during that timeframe' },
          { id: 'opt4', text: 'The market has zero risk' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Heavy volume indicates high institutional and retail participation, validating liquidity at those price levels.',
      },
      {
        id: 'q3',
        question: 'Why should traders be cautious of price spikes that happen on very low trading volume?',
        options: [
          { id: 'opt1', text: 'Low-volume spikes can be easily manipulated or lack widespread market conviction' },
          { id: 'opt2', text: 'Low volume guarantees the price will multiply tenfold' },
          { id: 'opt3', text: 'Low volume makes transaction fees negative' },
          { id: 'opt4', text: 'Low volume turns spot trades into futures contracts' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Low volume moves lack broad support and can quickly reverse once genuine liquidity enters the book.',
      },
      {
        id: 'q4',
        question: 'Where is volume typically displayed on technical candlestick charts?',
        options: [
          { id: 'opt1', text: 'As vertical bars along the bottom sub-panel corresponding to each time candle' },
          { id: 'opt2', text: 'As diagonal lines across the middle of the screen' },
          { id: 'opt3', text: 'In the website header navigation dropdown' },
          { id: 'opt4', text: 'In the browser’s URL address bar' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Chart platforms show volume as vertical bars beneath the candlestick price action for each corresponding interval.',
      },
      {
        id: 'q5',
        question: 'How does healthy 24-hour volume benefit everyday traders?',
        options: [
          { id: 'opt1', text: 'It provides tighter spreads and lower slippage when entering and exiting positions' },
          { id: 'opt2', text: 'It guarantees that every trade will be profitable' },
          { id: 'opt3', text: 'It eliminates the need for risk management' },
          { id: 'opt4', text: 'It fixes the market price permanently' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Higher liquidity means more active participants, narrower bid-ask spreads, and lower transaction execution cost.',
      },
    ],
  },

  // =========================================================================
  // CATEGORY 4: RISK MANAGEMENT (2 Quizzes)
  // =========================================================================
  {
    id: 'quiz-what-is-risk-management',
    lessonId: 'what-is-risk-management',
    title: 'What Is Risk Management? — Assessment',
    category: 'risk_management',
    categoryLabel: 'Risk Management',
    difficulty: 'BEGINNER',
    estimatedMinutes: 3,
    description: 'Check your knowledge of capital preservation, risk-to-reward principles, and surviving market drawdowns.',
    questions: [
      {
        id: 'q1',
        question: 'What is the primary objective of risk management in trading?',
        options: [
          { id: 'opt1', text: 'To preserve capital so the trader can survive adverse market conditions and remain in the game' },
          { id: 'opt2', text: 'To predict every market top and bottom with 100% accuracy' },
          { id: 'opt3', text: 'To eliminate all uncertainty from financial markets' },
          { id: 'opt4', text: 'To maximize leverage on every single trade' },
        ],
        correctOptionId: 'opt1',
        explanation: 'The foremost goal of risk management is capital preservation; without capital, a trader cannot participate in future opportunities.',
      },
      {
        id: 'q2',
        question: 'What is portfolio concentration risk?',
        options: [
          { id: 'opt1', text: 'Allocating too large a percentage of total portfolio capital into a single asset or trade' },
          { id: 'opt2', text: 'Holding too many different cryptocurrencies across different sectors' },
          { id: 'opt3', text: 'Using multiple web browsers simultaneously' },
          { id: 'opt4', text: 'Trading only during European market hours' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Over-concentrating in a single asset means an adverse event in that asset can inflict catastrophic damage on the overall portfolio.',
      },
      {
        id: 'q3',
        question: 'Why is avoiding severe portfolio drawdowns mathematically crucial for long-term recovery?',
        options: [
          { id: 'opt1', text: 'A 50% loss requires a 100% gain just to break even, and deeper losses require exponentially higher gains' },
          { id: 'opt2', text: 'Because portfolio recovery percentage is always exactly equal to loss percentage' },
          { id: 'opt3', text: 'Because losing 90% of a portfolio requires only a 10% gain to recover' },
          { id: 'opt4', text: 'Drawdown mathematics do not apply to digital assets' },
        ],
        correctOptionId: 'opt1',
        explanation: 'As drawdowns deepen, the percentage gain required to return to break-even grows exponentially (e.g. 50% loss needs +100%; 80% loss needs +400%).',
      },
      {
        id: 'q4',
        question: 'What does the Trade Coach in Crypto Compass evaluate before you place a trade?',
        options: [
          { id: 'opt1', text: 'Cash allocation, holding concentration, and portfolio risk exposure' },
          { id: 'opt2', text: 'Whether you will definitely make a profit tomorrow' },
          { id: 'opt3', text: 'Which coin has the best meme potential' },
          { id: 'opt4', text: 'Your personal bank credit score' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Trade Coach is an educational feature analyzing proposed trade size against cash balance and post-trade concentration.',
      },
      {
        id: 'q5',
        question: 'Which behavior is considered a hallmark of reckless risk management?',
        options: [
          { id: 'opt1', text: 'Betting 100% of your account on a single volatile asset without an exit plan ("going all-in")' },
          { id: 'opt2', text: 'Maintaining cash reserves to cushion against market volatility' },
          { id: 'opt3', text: 'Practicing in a simulated paper trading environment' },
          { id: 'opt4', text: 'Limiting individual trade risk to a modest percentage of total capital' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Committing all capital to a single unhedged position exposes the portfolio to total wipeout risk.',
      },
    ],
  },
  {
    id: 'quiz-position-sizing-basics',
    lessonId: 'position-sizing-basics',
    title: 'Position Sizing Basics — Assessment',
    category: 'risk_management',
    categoryLabel: 'Risk Management',
    difficulty: 'BEGINNER',
    estimatedMinutes: 3,
    description: 'Assess your comprehension of position sizing rules, risk-per-trade limits, and cash allocation discipline.',
    questions: [
      {
        id: 'q1',
        question: 'What does "position sizing" refer to in portfolio management?',
        options: [
          { id: 'opt1', text: 'Determining the exact dollar amount or quantity of an asset to allocate to a single trade' },
          { id: 'opt2', text: 'The physical screen resolution of the trading chart window' },
          { id: 'opt3', text: 'The font size used in order book ticket displays' },
          { id: 'opt4', text: 'The total number of coins minted at network inception' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Position sizing is the deliberate calculation of how much capital to commit to a position relative to overall portfolio value.',
      },
      {
        id: 'q2',
        question: 'If a learner has a $10,000 virtual portfolio and decides to risk no more than 2% of total capital on a trade, what is the maximum risk amount?',
        options: [
          { id: 'opt1', text: '$20' },
          { id: 'opt2', text: '$200' },
          { id: 'opt3', text: '$2,000' },
          { id: 'opt4', text: '$5,000' },
        ],
        correctOptionId: 'opt2',
        explanation: '2% of $10,000 is calculated as $10,000 × 0.02 = $200 maximum acceptable risk.',
      },
      {
        id: 'q3',
        question: 'Why should position size be adjusted based on an asset’s volatility?',
        options: [
          { id: 'opt1', text: 'More volatile assets should generally have smaller position sizes to keep dollar risk manageable' },
          { id: 'opt2', text: 'More volatile assets should always receive 100% of available capital' },
          { id: 'opt3', text: 'Volatility has no relationship to portfolio risk' },
          { id: 'opt4', text: 'Exchange software automatically doubles position size during market dips' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Because highly volatile assets experience wider percentage swings, smaller position sizes are required to maintain equal risk exposure.',
      },
      {
        id: 'q4',
        question: 'What is the danger of committing over 50% of your total cash to a single trade?',
        options: [
          { id: 'opt1', text: 'It creates VERY HIGH risk exposure and leaves little liquidity to absorb market downturns' },
          { id: 'opt2', text: 'It triggers an automatic suspension of your computer’s operating system' },
          { id: 'opt3', text: 'It eliminates all transaction fees on the exchange' },
          { id: 'opt4', text: 'It guarantees that the trade will be profitable' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Allocating >50% of cash leaves the portfolio severely illiquid and highly vulnerable to single-asset drawdowns.',
      },
      {
        id: 'q5',
        question: 'What is the primary benefit of maintaining an unallocated cash reserve in your virtual wallet?',
        options: [
          { id: 'opt1', text: 'It provides liquidity, emotional resilience, and the flexibility to act on future opportunities' },
          { id: 'opt2', text: 'Cash balances are guaranteed to double every calendar quarter' },
          { id: 'opt3', text: 'Cash in a crypto wallet earns mining rewards from Bitcoin nodes' },
          { id: 'opt4', text: 'It prevents cryptocurrency prices from moving' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Cash reserves buffer against volatility drawdowns and prevent learners from feeling forced to sell at disadvantageous moments.',
      },
    ],
  },

  // =========================================================================
  // CATEGORY 5: TRADING DISCIPLINE (2 Quizzes)
  // =========================================================================
  {
    id: 'quiz-trading-with-a-plan',
    lessonId: 'trading-with-a-plan',
    title: 'Trading With a Plan — Assessment',
    category: 'trading_discipline',
    categoryLabel: 'Trading Discipline',
    difficulty: 'BEGINNER',
    estimatedMinutes: 3,
    description: 'Check your knowledge of pre-trade preparation, defined entry/exit rules, and emotional discipline.',
    questions: [
      {
        id: 'q1',
        question: 'Why is having a documented trading plan essential before opening a position?',
        options: [
          { id: 'opt1', text: 'It removes impulsive decision-making by establishing clear entry, exit, and risk boundaries in advance' },
          { id: 'opt2', text: 'It legally guarantees that every trade will close in profit' },
          { id: 'opt3', text: 'It is a mandatory government filing requirement for paper trading' },
          { id: 'opt4', text: 'It speeds up blockchain block generation time' },
        ],
        correctOptionId: 'opt1',
        explanation: 'A trading plan establishes objective rules before emotions like fear and greed distort judgment during live market action.',
      },
      {
        id: 'q2',
        question: 'Which of the following elements should be defined in a sound trading plan BEFORE executing a trade?',
        options: [
          { id: 'opt1', text: 'Entry price criteria, maximum risk limit, and planned take-profit / exit points' },
          { id: 'opt2', text: 'How to spend potential future speculative millions' },
          { id: 'opt3', text: 'Excuses to blame external market participants if the trade loses' },
          { id: 'opt4', text: 'The secret passphrase to bypass exchange risk controls' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Comprehensive plans define entry rationale, position sizing, invalidation level (stop loss), and profit targets before executing.',
      },
      {
        id: 'q3',
        question: 'What is the psychological risk of trading without a predefined plan?',
        options: [
          { id: 'opt1', text: 'Traders easily fall prey to emotional panic selling at bottoms and greedy buying at tops' },
          { id: 'opt2', text: 'The trading software will refuse to register any keystrokes' },
          { id: 'opt3', text: 'Unplanned trades always earn higher returns than planned trades' },
          { id: 'opt4', text: 'There is no emotional risk in financial markets' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Without rules, traders react reactively to market noise, chasing rallies and panic-dumping into drawdowns.',
      },
      {
        id: 'q4',
        question: 'When should a trader evaluate and reflect on trade performance?',
        options: [
          { id: 'opt1', text: 'During post-trade review using an objective chronological trading ledger' },
          { id: 'opt2', text: 'Only when bragging on social media forums' },
          { id: 'opt3', text: 'Never, because past trades should be completely forgotten' },
          { id: 'opt4', text: 'Only after wiping out all available virtual cash' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Reviewing executed trades in a history ledger helps identify behavioral patterns and adherence to plans.',
      },
      {
        id: 'q5',
        question: 'How should a disciplined trader handle an inevitable losing trade?',
        options: [
          { id: 'opt1', text: 'Accept the controlled loss as a normal cost of doing business and review adherence to the plan' },
          { id: 'opt2', text: 'Immediately double the position size to "revenge trade" and win the money back' },
          { id: 'opt3', text: 'Deny that the loss occurred and borrow additional funds' },
          { id: 'opt4', text: 'Blame the blockchain validators' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Losses are unavoidable in market participation; disciplined traders accept controlled losses and avoid emotional revenge trading.',
      },
    ],
  },
  {
    id: 'quiz-common-beginner-mistakes',
    lessonId: 'common-beginner-mistakes',
    title: 'Common Beginner Trading Mistakes — Assessment',
    category: 'trading_discipline',
    categoryLabel: 'Trading Discipline',
    difficulty: 'BEGINNER',
    estimatedMinutes: 3,
    description: 'Assess your ability to recognize and avoid common psychological traps like FOMO, revenge trading, and over-leveraging.',
    questions: [
      {
        id: 'q1',
        question: 'What does the acronym "FOMO" stand for in trading psychology?',
        options: [
          { id: 'opt1', text: 'Fear Of Missing Out' },
          { id: 'opt2', text: 'Frequency Of Market Orders' },
          { id: 'opt3', text: 'Fixed Option Maturity Operation' },
          { id: 'opt4', text: 'Fractional Ownership Mining Output' },
        ],
        correctOptionId: 'opt1',
        explanation: 'FOMO (Fear Of Missing Out) describes the emotional impulse to buy an asset after it has already surged dramatically.',
      },
      {
        id: 'q2',
        question: 'Why is buying an asset out of pure FOMO after a parabolic price rally dangerous for beginners?',
        options: [
          { id: 'opt1', text: 'Late buyers often enter at peak euphoric prices right before a sharp market correction occurs' },
          { id: 'opt2', text: 'FOMO trades automatically delete the user’s virtual wallet' },
          { id: 'opt3', text: 'Exchanges prohibit purchases of rising assets' },
          { id: 'opt4', text: 'All parabolic rallies continue upward forever' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Chasing extended rallies often leaves buyers holding the top when early participants take profits.',
      },
      {
        id: 'q3',
        question: 'What is "revenge trading"?',
        options: [
          { id: 'opt1', text: 'Irrationally opening large, hasty trades immediately after a loss to quickly recover lost capital' },
          { id: 'opt2', text: 'Reporting an exchange outage to regulatory authorities' },
          { id: 'opt3', text: 'Exercising legal contract rights against a counterparty' },
          { id: 'opt4', text: 'Switching between Bitcoin and Ethereum' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Revenge trading is emotional gambling driven by anger over a previous loss, typically accelerating capital destruction.',
      },
      {
        id: 'q4',
        question: 'What is "over-trading"?',
        options: [
          { id: 'opt1', text: 'Trading excessively without high-probability setups, generating unnecessary transaction costs and mental fatigue' },
          { id: 'opt2', text: 'Submitting more than one trade in a calendar year' },
          { id: 'opt3', text: 'Reading educational lessons for more than 15 minutes' },
          { id: 'opt4', text: 'Holding cash in a virtual wallet' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Over-trading stems from impatience or addiction to action rather than patience waiting for quality setups.',
      },
      {
        id: 'q5',
        question: 'What is the most effective approach for a beginner to protect their psychology and capital while learning?',
        options: [
          { id: 'opt1', text: 'Practice methodically in a risk-free paper trading sandbox while studying core educational concepts' },
          { id: 'opt2', text: 'Follow anonymous social media trading influencers with real life savings' },
          { id: 'opt3', text: 'Trade exclusively with borrowed funds to maximize potential returns' },
          { id: 'opt4', text: 'Rely purely on gut intuition without reviewing trade history' },
        ],
        correctOptionId: 'opt1',
        explanation: 'Paper trading with virtual funds paired with structured curriculum builds conceptual confidence with zero real financial risk.',
      },
    ],
  },
];

module.exports = {
  QUIZZES,
};
